version: '3.9'
services:
  chatbot-app:
    container_name: chatbot-frontend
    build: ./chatbot-app
    ports:
      - 3000:3000
    working_dir: /chatbot-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3000']
      timeout: 10s
      retries: 5
    volumes:
      - ./chatbot-app/src:/chatbot-frontend/src
  chatbot-api:
    container_name: chatbot-backend
    build: ./chatbot-api
    ports:
      - 3001:3001
    working_dir: /chatbot-backend
    command: npm run start
    volumes:
      - ./chatbot-api/src:/chatbot-backend/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
